[project]
name = "othellox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Libin Lalu", email = "libinlalu000@gmail.com" }
]
requires-python = ">=3.15"
dependencies = [
    "textual>=8.2.3",
    "textual-dev>=1.8.0",
]

[project.scripts]
othellox = "othellox.main:run"

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"
